### ISSUE TITLE
missing dependency for symfony/debug cause below error when migration taken place

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-migration#1]
Fatal error: Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found in /usr/local/zendphp7/var/apps/http/maintenance.zenddev.ftr.com/80/1.1.4_2334/vendor/symfony/console/Application.php:134
Stack trace:
#0 /usr/local/zendphp7/var/apps/http/maintenance.zenddev.ftr.com/80/1.1.4_2334/vendor/zendframework/zend-expressive-migration/bin/expressive-migration(20): Symfony\Component\Console\Application->run()
#1 {main}
  thrown in /usr/local/zendphp7/var/apps/http/maintenance.zenddev.ftr.com/80/1.1.4_2334/vendor/symfony/console/Application.php on line 134

when checked in vendor/symfony debug was missing. It was exist there before running " ./vendor/bin/expressive-migration migrate". got removed after running migrate command.

---

Originally posted by @toralpatelin at https://github.com/zendframework/zend-expressive-migration/issues/13

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
