### ISSUE TITLE
Script to build phar library

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-migration#4]
For releases, probably we need to do also something like:
https://github.com/composer/composer/blob/master/.travis.yml#L64-L72

and would be nice to have also check in travis for if build is correct:
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/.travis.yml#L44-L45

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-expressive-migration/pull/2

**Comment by weierophinney** [comment]
This is an awesome idea, but to make usage of a PHAR secure, we need to sign it and distribute a signature as well... which is non-trivial (I know, as I've done it in the past, and setting up the toolchain is ridiculous ([see my writeup](https://mwop.net/blog/2015-12-14-secure-phar-automation.html)), even without doing rollback and self-update automation.

We can discuss after the initial release; usage of composer is easier initially and reasonably secure as developers can compare the installed sources with the github repo.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-expressive-migration/pull/2#issuecomment-373184969

**Comment by internalsystemerror** [comment]
For consideration:
[PHIVE](https://phar.io/)
[GitHub Release Assets](https://docs.github.com/en/rest/reference/repos#upload-a-release-asset)

**Comment by weierophinney** [comment]
@internalsystemerror I've done this for [phly/keep-a-changelog](/phly/keep-a-changelog) at this point, so I know ways we can do it with GHA relatively easily. I'm not 100% convinced it makes sense at this point, though; we get ~30 installs a day currently, and I'm not sure this level of activity warrants the time investment.

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
